CREATE TABLE IF NOT EXISTS APPLICANT (
    ApplicantNo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IsFirstTime BOOLEAN NOT NULL,
    LastExaminationTaken DATE,
    CSCRegionalOffice VARCHAR(10),
    ExaminationDate DATE,
    Examinationplace VARCHAR(50),
    VerifiedAgainst VARCHAR(10),
    ApplicantPhotoURL VARCHAR(255) NOT NULL,
    ApplicantSignatureURL VARCHAR(255) NOT NULL,
    ApplicantName VARCHAR(100) NOT NULL,
    Age INT NOT NULL,
    Birthdate DATE NOT NULL,
    Sex CHAR(1) NOT NULL,
    Birthplace VARCHAR(50) NOT NULL,
    Citizenship VARCHAR(50) NOT NULL,
    MotherMaidenName VARCHAR(50) NOT NULL,
    PermanentMailingAddress VARCHAR(100) NOT NULL,
    CivilStatus VARCHAR(2) NOT NULL,
    IsPregnant BOOLEAN NOT NULL,
    IsSeniorCitizen BOOLEAN NOT NULL,
    PWD VARCHAR(50),
    MobileNumber VARCHAR(11) NOT NULL,
    Telephone VARCHAR(15),
    EmailAddress VARCHAR(50),
    EmploymentType VARCHAR(3),
    HighestEducLevel VARCHAR(50),
    Completion VARCHAR(2),
    GraduationDate DATE,
    HonorsReceived VARCHAR(20),
    NGHighestAttained VARCHAR(25),
    TitleOfDegree VARCHAR(50),
    Major VARCHAR(50),
    SchoolStartYear INT,
    SchoolEndYear INT
);

CREATE TABLE IF NOT EXISTS EXISTING_EXAMINATION(
    ApplicantNo INT NOT NULL,
    ExistingExaminationSeq INT NOT NULL,
    ExistingExaminationTitle VARCHAR(50) NOT NULL,
    ExistingExaminationRating DECIMAL(5,2) NOT NULL,
    ExistingExaminationDate DATE NOT NULL,
    ExistingExaminationPlace VARCHAR(100) NOT NULL,
    PRIMARY KEY(ApplicantNo, ExistingExaminationSeq),
    FOREIGN KEY(ApplicantNo) REFERENCES Applicant(ApplicantNo)
);
