CREATE TABLE IF NOT EXISTS APPLICANT (
    ApplicantNo INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Age INT NOT NULL,
    Sex CHAR(1) NOT NULL,
    Birthdate DATE NOT NULL,
    Birthplace VARCHAR(50) NOT NULL,
    Citizenship VARCHAR(50) NOT NULL,
    Photo VARCHAR(255) NOT NULL
);
