export const REGIONAL_OFFICES = [
    { value: "I", label: "Regional Office I" },
    { value: "II", label: "Regional Office II" },
    { value: "III", label: "Regional Office III" },
    { value: "IV", label: "Regional Office IV" },
    { value: "MIMAROPA", label: "Regional Office MIMAROPA" },
    { value: "V", label: "Regional Office V" },
    { value: "VI", label: "Regional Office VI" },
    { value: "VII", label: "Regional Office VII" },
    { value: "VIII", label: "Regional Office VIII" },
    { value: "IX", label: "Regional Office IX" },
    { value: "X", label: "Regional Office X" },
    { value: "XI", label: "Regional Office XI" },
    { value: "XII", label: "Regional Office XII" },
    { value: "XIII", label: "Regional Office XIII" },
    { value: "NCR", label: "Regional Office NCR" },
    { value: "CAR", label: "Regional Office CAR" },
    { value: "BARMM", label: "Regional Office BARMM" },
    { value: "NIR", label: "Regional Office NIR" },
];

export const CITIZENSHIPS = [
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "American", label: "American" },
  { value: "Andorran", label: "Andorran" },
  { value: "Angolan", label: "Angolan" },
  { value: "Antiguan and Barbudan", label: "Antiguan and Barbudan" },
  { value: "Argentine", label: "Argentine" },
  { value: "Armenian", label: "Armenian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Azerbaijani", label: "Azerbaijani" },

  { value: "Bahamian", label: "Bahamian" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Barbadian", label: "Barbadian" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Belgian", label: "Belgian" },
  { value: "Belizean", label: "Belizean" },
  { value: "Beninese", label: "Beninese" },
  { value: "Bhutanese", label: "Bhutanese" },
  { value: "Bolivian", label: "Bolivian" },
  { value: "Bosnian and Herzegovinian", label: "Bosnian and Herzegovinian" },
  { value: "Botswanan", label: "Botswanan" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burkinabé", label: "Burkinabé" },
  { value: "Burundian", label: "Burundian" },

  { value: "Cambodian", label: "Cambodian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Cape Verdean", label: "Cape Verdean" },
  { value: "Central African", label: "Central African" },
  { value: "Chadian", label: "Chadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Comorian", label: "Comorian" },
  { value: "Congolese (Congo-Brazzaville)", label: "Congolese (Congo-Brazzaville)" },
  { value: "Congolese (DRC)", label: "Congolese (DRC)" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croatian", label: "Croatian" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "Czech", label: "Czech" },

  { value: "Danish", label: "Danish" },
  { value: "Djiboutian", label: "Djiboutian" },
  { value: "Dominican", label: "Dominican" },

  { value: "Ecuadorian", label: "Ecuadorian" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Salvadoran", label: "Salvadoran" },
  { value: "Equatorial Guinean", label: "Equatorial Guinean" },
  { value: "Eritrean", label: "Eritrean" },
  { value: "Estonian", label: "Estonian" },
  { value: "Eswatini", label: "Eswatini" },
  { value: "Ethiopian", label: "Ethiopian" },

  { value: "Fijian", label: "Fijian" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },

  { value: "Gabonese", label: "Gabonese" },
  { value: "Gambian", label: "Gambian" },
  { value: "Georgian", label: "Georgian" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Grenadian", label: "Grenadian" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Guinean", label: "Guinean" },
  { value: "Guinea-Bissauan", label: "Guinea-Bissauan" },
  { value: "Guyanese", label: "Guyanese" },

  { value: "Haitian", label: "Haitian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },

  { value: "Icelandic", label: "Icelandic" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },

  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },

  { value: "Kazakh", label: "Kazakh" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Kyrgyz", label: "Kyrgyz" },

  { value: "Lao", label: "Lao" },
  { value: "Latvian", label: "Latvian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Liberian", label: "Liberian" },
  { value: "Libyan", label: "Libyan" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Luxembourgish", label: "Luxembourgish" },

  { value: "Malagasy", label: "Malagasy" },
  { value: "Malawian", label: "Malawian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivian", label: "Maldivian" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Marshallese", label: "Marshallese" },
  { value: "Mauritanian", label: "Mauritanian" },
  { value: "Mauritian", label: "Mauritian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Micronesian", label: "Micronesian" },
  { value: "Moldovan", label: "Moldovan" },
  { value: "Monegasque", label: "Monegasque" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Montenegrin", label: "Montenegrin" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Myanmar", label: "Myanmar" },

  { value: "Namibian", label: "Namibian" },
  { value: "Nauruan", label: "Nauruan" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "Dutch", label: "Dutch" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerien", label: "Nigerien" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "North Korean", label: "North Korean" },
  { value: "North Macedonian", label: "North Macedonian" },
  { value: "Norwegian", label: "Norwegian" },

  { value: "Omani", label: "Omani" },

  { value: "Pakistani", label: "Pakistani" },
  { value: "Palauan", label: "Palauan" },
  { value: "Palestinian", label: "Palestinian" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Papua New Guinean", label: "Papua New Guinean" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Filipino", label: "Filipino" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },

  { value: "Qatari", label: "Qatari" },

  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Rwandan", label: "Rwandan" },

  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  { value: "Saint Lucian", label: "Saint Lucian" },
  { value: "Saint Vincentian", label: "Saint Vincentian" },
  { value: "Samoan", label: "Samoan" },
  { value: "San Marinese", label: "San Marinese" },
  { value: "Sao Tomean", label: "Sao Tomean" },
  { value: "Saudi", label: "Saudi" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Seychellois", label: "Seychellois" },
  { value: "Sierra Leonean", label: "Sierra Leonean" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovak", label: "Slovak" },
  { value: "Slovenian", label: "Slovenian" },
  { value: "Solomon Islander", label: "Solomon Islander" },
  { value: "Somali", label: "Somali" },
  { value: "South African", label: "South African" },
  { value: "South Korean", label: "South Korean" },
  { value: "South Sudanese", label: "South Sudanese" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Sudanese", label: "Sudanese" },
  { value: "Surinamese", label: "Surinamese" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },

  { value: "Taiwanese", label: "Taiwanese" },
  { value: "Tajik", label: "Tajik" },
  { value: "Tanzanian", label: "Tanzanian" },
  { value: "Thai", label: "Thai" },
  { value: "Timorese", label: "Timorese" },
  { value: "Togolese", label: "Togolese" },
  { value: "Tongan", label: "Tongan" },
  { value: "Trinidadian and Tobagonian", label: "Trinidadian and Tobagonian" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Turkmen", label: "Turkmen" },
  { value: "Tuvaluan", label: "Tuvaluan" },

  { value: "Ugandan", label: "Ugandan" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Emirati", label: "Emirati" },
  { value: "British", label: "British" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Uzbek", label: "Uzbek" },

  { value: "Vanuatuan", label: "Vanuatuan" },
  { value: "Vatican", label: "Vatican" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },

  { value: "Yemeni", label: "Yemeni" },

  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" }
];

export const CIVIL_STATUS = [
  { value: "S", label: "Single" },
  { value: "M", label: "Married" },
  { value: "W", label: "Widowed" },
  { value: "D", label: "Divorced" },
  { value: "LS", label: "Legally Separated" },
  { value: "A", label: "Annulled" },
];

export const EMPLOYMENT_STATUS = [
  { value: "REG", label: "Regular" },
  { value: "PJ", label: "Project Based/Job Order" },
  { value: "PRO", label: "Probational" },
  { value: "SEA", label: "Seasonal" },
  { value: "FT", label: "Fixed-Term/Contractual" },
];
